name: lint checks

run-name: code linting
on: pull_request

jobs:
  lint-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install NodeJS
        uses: actions/setup-node@v3

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: latest

      - name: Install deps
        run: pnpm i --frozen-lockfile

      - name: Run typescript compiler check
        run: pnpm tsc

      - name: Run eslint check
        run: pnpm eslint

      - name: Run prettier check
        run: pnpm prettier --check