name: ts-lint-check
run-name: ts check
on:
  push
jobs:
  ts-lint-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install NodeJS
        uses: actions/setup-node@v3

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: latest
          run_install:
            - recursive: true
            - args: [--frozen-lockfile, typescript]
      - run: pnpm i
      - run: tsc
